module LighthouseBGS
  class BenefitClaimService < LighthouseBGS::Base
    def bean_name
      'BenefitClaimServiceBean'
    end

    def self.service_name
      'benefit_claim_web'
    end

    # either date_of_claim OR suspense_date must be populated mm/dd/yyyy
    def insert_benefit_claim(
      file_number:,
      ssn:,
      benefit_claim_type:,
      payee:,
      end_product:,
      end_product_code:,
      first_name:,
      last_name:,
      city:,
      state:,
      postal_code:,
      country:,
      disposition:,
      section_unit_no:,
      folder_with_claim:,
      end_product_name:,
      pre_discharge_indicator:,
      date_of_claim: nil,
      title_name: nil,
      middle_name: nil,
      suffix_name: nil,
      address_line1: nil,
      address_line2: nil,
      address_line3: nil,
      postal_code_plus4: nil,
      day_time_area_code: nil,
      day_time_phone_number: nil,
      night_time_area_code: nil,
      night_time_phone_number: nil,
      email_address: nil,
      suspense_date: nil,
      future_reason: nil,
      claimant_ssn: nil,
      beneficiary_date_of_birth: nil,
      power_of_attorney: nil,
      guf_war_registry_permit: nil,
      suppress_acknowledgement_letter: nil,
      special_issue_case: nil,
      in_take_site: nil,
      soj: nil,
      mlty_postal_type_cd: nil,
      mlty_post_office_type_cd: nil,
      foreign_mail_code: nil,
      address_type: nil,
      bypass_indicator: nil,
      bnft_claim_id: nil,
      allowPoaAccess: nil,
      allowPoaCadd: nil,
      submtrRoleTypeCd: nil,
      submtrApplcnTypeCd: nil,
      awardSoj: nil,
      powNumberOfDays: nil,
      homelessIndicator: nil,
      ptcpntIdClaimant: nil,
      preDschrgTypeCd: nil,
      personOrgInd: nil,
      payeeOrgName: nil,
      payeeOrgType: nil,
      payeeOrgTitle: nil,
      groupOneValidatedInd: nil,
      prvncNm: nil,
      trtryNm: nil,
      treasuryMailingAddress1: nil,
      treasuryMailingAddress2: nil,
      treasuryMailingAddress3: nil,
      treasuryMailingAddress4: nil,
      treasuryMailingAddress5: nil,
      treasuryMailingAddress6: nil,
      fiduciaryOneLastName: nil,
      fiduciaryOneFirstName: nil,
      fiduciaryOneMiddleName: nil,
      fiduciaryOneSuffixName: nil,
      fiduciaryOrgName: nil,
      ptcpntIdFiduciaryOne: nil,
      fiduciaryOrgTitle: nil,
      fiduciaryOrgType: nil,
      fiduciaryPrepPhraseType: nil
    )

      response = request(
        :insert_benefit_claim,
        {

          "benefitClaimInput": {
            "fileNumber": file_number,
            "ssn": ssn,
            "benefitClaimType": benefit_claim_type,
            "payee": payee,
            "endProduct": end_product,
            "endProductCode": end_product_code,
            "firstName": first_name,
            "lastName": last_name,
            "city": city,
            "state": state,
            "postalCode": postal_code,
            "country": country,
            "disposition": disposition,
            "sectionUnitNo": section_unit_no,
            "folderWithClaim": folder_with_claim,
            "endProductName": end_product_name,
            "preDischargeIndicator": pre_discharge_indicator,
            "dateOfClaim": date_of_claim,
            "titleName": title_name,
            "middleName": middle_name,
            "suffixName": suffix_name,
            "addressLine1": address_line1,
            "addressLine2": address_line2,
            "addressLine3": address_line3,
            "postalCodePlus4": postal_code_plus4,
            "dayTimeAreaCode": day_time_area_code,
            "dayTimePhoneNumber": day_time_phone_number,
            "nightTimeAreaCode": night_time_area_code,
            "nightTimePhoneNumber": night_time_phone_number,
            "emailAddress": email_address,
            "suspenseDate": suspense_date,
            "futureReason": future_reason,
            "claimantSsn": claimant_ssn,
            "beneficiaryDateOfBirth": beneficiary_date_of_birth,
            "powerOfAttorney": power_of_attorney,
            "gulfWarRegistryPermit": guf_war_registry_permit,
            "suppressAcknowledgementLetter": suppress_acknowledgement_letter,
            "specialIssueCase": special_issue_case,
            "inTakeSite": in_take_site,
            "soj": soj,
            "mltyPostalTypeCd": mlty_postal_type_cd,
            "mltyPostOfficeTypeCd": mlty_post_office_type_cd,
            "foreignMailCode": foreign_mail_code,
            "addressType": address_type,
            "bypassIndicator": bypass_indicator,
            "bnftClaimId": bnft_claim_id,
            "allowPoaAccess": allowPoaAccess,
            "allowPoaCadd": allowPoaCadd,
            "submtrRoleTypeCd": submtrRoleTypeCd,
            "submtrApplcnTypeCd": submtrApplcnTypeCd,
            "awardSoj": awardSoj,
            "powNumberOfDays": powNumberOfDays,
            "homelessIndicator": homelessIndicator,
            "ptcpntIdClaimant": ptcpntIdClaimant,
            "preDschrgTypeCd": preDschrgTypeCd,
            "personOrgInd": personOrgInd,
            "payeeOrgName": payeeOrgName,
            "payeeOrgType": payeeOrgType,
            "payeeOrgTitle": payeeOrgTitle,
            "groupOneValidatedInd": groupOneValidatedInd,
            "prvncNm": prvncNm,
            "trtryNm": trtryNm,
            "treasuryMailingAddress1": treasuryMailingAddress1,
            "treasuryMailingAddress2": treasuryMailingAddress2,
            "treasuryMailingAddress3": treasuryMailingAddress3,
            "treasuryMailingAddress4": treasuryMailingAddress4,
            "treasuryMailingAddress5": treasuryMailingAddress5,
            "treasuryMailingAddress6": treasuryMailingAddress6,
            "fiduciaryOneLastName": fiduciaryOneLastName,
            "fiduciaryOneFirstName": fiduciaryOneFirstName,
            "fiduciaryOneMiddleName": fiduciaryOneMiddleName,
            "fiduciaryOneSuffixName": fiduciaryOneSuffixName,
            "fiduciaryOrgName": fiduciaryOrgName,
            "ptcpntIdFiduciaryOne": ptcpntIdFiduciaryOne,
            "fiduciaryOrgTitle": fiduciaryOrgTitle,
            "fiduciaryOrgType": fiduciaryOrgType,
            "fiduciaryPrepPhraseType": fiduciaryPrepPhraseType
          }
        },
        ssn
      )

      response.body[:insert_benefit_claim_response][:return]
    end
  end
end
