name: Bundle Audit

on:
  push:

jobs:
  bundle-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.3'
      - name: Install dependencies
        run: bundle install
      - name: Bundle Audit
        run: bundle exec bundle-audit check --update
