name: Specs

on:
  push:

jobs:
  bundle-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.3'
      - name: Install dependencies
        run: bundle install
      - name: Run all RSpec specs
        run: |
          bundle exec rspec --pattern $(cat /tmp/tests-to-run) --format progress
          --format RspecJunitFormatter -o /tmp/rspec/rspec.xml
