name: Test and Build

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.3'
      - name: Install dependencies
        run: bundle install
      - name: Bundle Audit
        run: bundle exec bundle-audit check --update
      - name: Lint code with Rubocop
        run: |
          bundle exec rubocop -r rubocop-thread_safety --parallel --format
          progress --format RuboCop::Formatter::JUnitFormatter
      - name: Run all RSpec specs
        run: |
          bundle exec rspec --pattern $(cat /tmp/tests-to-run) --format progress
          --format RspecJunitFormatter -o /tmp/rspec/rspec.xml
